### ISSUE TITLE
Add space before entries in the attached line

### ISSUE THREAD

**Issue by akashmahale** [SAM10795/AnistreamIN#4]
https://github.com/SAM10795/AnistreamIN/blob/b8c47f16382300fe6c3fe3b6fd1b43a44033c442/script.js#L502
![image](https://user-images.githubusercontent.com/16264387/95660376-ff124080-0b44-11eb-80ed-0742f0762b18.png)

**Comment by akashmahale** [comment]
![image](https://user-images.githubusercontent.com/16264387/95660368-f28de800-0b44-11eb-8044-b8ddb89e1cc8.png)

**Comment by SAM10795** [comment]
Fixed in latest commit
